
development:
  adapter: mysql

  database: 73slove_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql
  database: 73slove_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql
  database: numly_73s
  username: numly_numly
  password: mwhmwh
  encoding: utf8
  